# Generated by Django 5.0.1 on 2024-03-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, verbose_name='Псевдоним')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False,  verbose_name='E-mail')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('photo', models.ImageField(blank=True, upload_to='users/<django.db.models.fields.EmailField>/photos', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Middle'), (3, 'Low')], default=1, verbose_name='Приоритет')),
                ('deadline', models.DateField(verbose_name='Дата закрытия задачи')),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('InProgress', 'In progress'), ('Done', 'Done')], default='Todo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Environment.project')),
                ('coworkers', models.ManyToManyField(related_name='tasks', to='Environment.user')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_tasks', to='Environment.user')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='coworkers',
            field=models.ManyToManyField(related_name='projects', to='Environment.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_projects', to='Environment.user'),
        ),
    ]
