# Generated by Django 5.0.1 on 2024-06-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Environment', '0002_user_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='coworkers',
        ),
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
        migrations.AddField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(related_name='tasks', to='Environment.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='Environment.user'),
        ),
    ]
