# Generated by Django 5.0.1 on 2024-06-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Environment', '0003_remove_task_coworkers_remove_task_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='Environment.user'),
        ),
    ]
