# Generated by Django 5.0.1 on 2024-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Environment', '0004_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coworkers',
            field=models.ManyToManyField(blank=True, related_name='projects', to='Environment.user'),
        ),
    ]
