# Generated by Django 5.0.1 on 2024-07-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Environment', '0005_alter_project_coworkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coworkers',
            field=models.ManyToManyField(related_name='projects', to='Environment.user'),
        ),
    ]
