# Generated by Django 5.0.1 on 2024-07-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Environment', '0006_alter_project_coworkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='coworkers',
            field=models.ManyToManyField(related_name='other_projects', to='Environment.user'),
        ),
    ]
