# Generated by Django 5.0.1 on 2024-07-17 16:19

import Environment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Environment', '0007_alter_project_coworkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', upload_to=Environment.models.user_directory_path, verbose_name='Фото', width_field='width'),
        ),
    ]
