# Generated by Django 5.0.1 on 2024-09-30 17:15

import Environment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Environment', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код подтверждения'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Статус подтверждения e-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=Environment.models.user_directory_path, verbose_name='Фото'),
        ),
    ]
